import Head from 'next/head';
import Sidebar from "../Components/Sidebar"
export default function Home() {
  return (
    <div >
      <Head>
        <title>Whatsapp2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Sidebar/>
    </div>
  )
}
